# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  name: 'Default'  # Your self-hosted agent

variables:
  buildConfiguration: 'Release'

steps:
# ✅ Install .NET SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '7.0.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

# ✅ Restore and Build (with Analyzers)
- script: |
    dotnet restore
    dotnet build --no-incremental --configuration $(buildConfiguration) -warnaserror
  displayName: 'Build the project with analyzers (fail on warnings)'

# ✅ Publish the app
- script: |
    dotnet publish -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)
  displayName: 'Publish the project'

# ✅ Upload build artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'mvc_app'
    publishLocation: 'Container'